name: Node.js CI
on: push
jobs:
  
  build-node:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    container: node:20.17.0
    steps:
  
    - run: node --version
    - run: npm --version
    - uses: actions/checkout@v3
    - run: npm install
    - run: node app.js
