name: Node.js CI
on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" # to check if MongoDB is ready

    steps:
    - uses: actions/checkout@v3
    - run: node --version
    - run: npm --version
    - run: npm install
    - run: node app.js
