name: Node.js CI

on: [push]

jobs:
  build-node:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Cache node_modules
      uses: actions/cache@v3
      id: node-modules-cache
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-modules-${{ runner.os }}-

    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Update express
      run: npm install express@5.0.1

    - name: Update mongoose
      run: npm update mongoose --depth 1

    - name: Fix vulnerabilities
      run: npm audit fix

    - name: Check for vulnerabilities
      run: npm audit

    - name: Wait for MongoDB to be fully ready
      run: sleep 10  # Ajout d'une pause plus longue pour éviter les problèmes

    - name: Run application in background
      run: npm start > server.log 2>&1 &

    - name: Show application logs
      run: sleep 5 && cat server.log  # Vérifier les logs après quelques secondes

    - name: Wait for server to be ready
      run: sleep 10  # Ajuste cette valeur selon ton application

    - name: Run tests (or check if app is running)
      run: curl --fail http://localhost:3000 || (echo "Server not responding" && cat server.log && exit 1)

    - name: Stop application
      run: pkill -f "node" || echo "No process found"
