name: Node.js CI with MongoDB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --host localhost --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.17.0
      uses: actions/setup-node@v4
      with:
        node-version: 20.17.0
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Wait for MongoDB
      run: |
        echo "Waiting for MongoDB to start..."
        until nc -z localhost 27017; do
          echo "Waiting for MongoDB..."
          sleep 5
        done
        echo "MongoDB is up and running!"

    - name: Start Application
      env:
        MONGODB_URI: mongodb://localhost:27017/myexam2025
      run: NODE_ENV=production npm start
